package server;


import Quiz_Game.Interface.Interface;
import java.awt.Color;
import java.awt.Point;
import java.awt.Window;
import java.rmi.Remote;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * This is the Server GUI.
 * It is used to start the RMI server 
 * @author  Rasu Mayurathan
 * @version 1.0
 * @since   2021-11-22
 */
public class The_Server extends javax.swing.JFrame {

    /**
     * Creates new form The_Server
     */
    public The_Server() {
        initComponents();
    }
    Point location;//Point class represents a location in a two-dimensional (x, y) coordinate space.
    Point pressed;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigation_bar = new javax.swing.JPanel();
        MinimizeBtn = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ServerImage = new javax.swing.JLabel();
        Start_ServerBtn = new javax.swing.JButton();
        Successlbl = new javax.swing.JLabel();
        Errorlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigation_bar.setBackground(new java.awt.Color(0, 0, 0));
        navigation_bar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(255, 255, 255)));
        navigation_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navigation_barMouseDragged(evt);
            }
        });
        navigation_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navigation_barMousePressed(evt);
            }
        });
        navigation_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimizeBtn.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 50)); // NOI18N
        MinimizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize-white-28.png"))); // NOI18N
        MinimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeBtnMouseClicked(evt);
            }
        });
        navigation_bar.add(MinimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        closeBtn.setFont(new java.awt.Font("Ubuntu Mono", 0, 35)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-white-28.png"))); // NOI18N
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        navigation_bar.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, 30));

        getContentPane().add(navigation_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        ServerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Server_3-transparent.png"))); // NOI18N

        Start_ServerBtn.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Start_ServerBtn.setForeground(new java.awt.Color(136, 133, 210));
        Start_ServerBtn.setText("START SERVER");
        Start_ServerBtn.setOpaque(false);
        Start_ServerBtn.setContentAreaFilled(false);
        Start_ServerBtn.setBorderPainted(true);
        Start_ServerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Start_ServerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Start_ServerBtnMouseExited(evt);
            }
        });
        Start_ServerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_ServerBtnActionPerformed(evt);
            }
        });

        Successlbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Successlbl.setForeground(new java.awt.Color(0, 255, 51));
        Successlbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 51)));

        Errorlbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Errorlbl.setForeground(new java.awt.Color(255, 51, 51));
        Errorlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MATH QUIZ SERVER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ServerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Successlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(Start_ServerBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(Errorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(ServerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Start_ServerBtn)
                .addGap(36, 36, 36)
                .addComponent(Successlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Errorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   /***
    * This event to start RMI server
    * @param evt 
    */
    private void Start_ServerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_ServerBtnActionPerformed

        try {

            /*The suspect that this block of statement can throw
            * exception so we handled it by placing these statements
            * inside try and handled the exception in catch block
             */
            Interface impl = new TheImplementation(); // Interface is creating an object using a TheImplementation
            Registry reg = LocateRegistry.createRegistry(1099);//Registry ie creating an object and locating the registry through the port number called 1099
            //we basically give the connection through this port
            reg.rebind("Server", (Remote) impl);//The sever name is RMI server

            Successlbl.setText("Service started. Welcome to the RMI Hello Service!");

        } catch (RemoteException e) {

            /* 
            *This block will only execute if any Remote exception occurs in try block
             */
            Errorlbl.setText("A Problem occured");

        }
    }//GEN-LAST:event_Start_ServerBtnActionPerformed

    private void navigation_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMousePressed
       //The "mouse pressed" event. This MouseEvent occurs when a mouse button is pushed down.
         pressed = evt.getLocationOnScreen();//Returns the absolute x, y position of the event.
         Window window = SwingUtilities.windowForComponent(evt.getComponent());  //Creating object of Window.
         location = window.getLocation();//Returns the absolute x, y position of the event.
    }//GEN-LAST:event_navigation_barMousePressed

    private void navigation_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigation_barMouseDragged
      //The "mouse dragged" event. This MouseEvent occurs when the mouse position changes while a mouse button is pressed.
        Point dragged = evt.getLocationOnScreen(); //Returns the absolute x, y position of the event.
        int x = (int)(location.x + dragged.getX() - pressed.getX());
        int y = (int)(location.y + dragged.getY() - pressed.getY());
        Window window = SwingUtilities.windowForComponent(evt.getComponent());
        window.setLocation(x, y);
    }//GEN-LAST:event_navigation_barMouseDragged

    private void MinimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeBtnMouseClicked
        //This code segment is used to minimize the jframe.
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        //This code segment is used to close the jframe.
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void Start_ServerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_ServerBtnMouseEntered
        //The "mouse entered" event. This MouseEvent occurs when the mouse cursor enters the unobscured part of component's geometry
        Start_ServerBtn.setForeground(new Color(255,255,255)); //Changing color to black
    }//GEN-LAST:event_Start_ServerBtnMouseEntered

    private void Start_ServerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_ServerBtnMouseExited
        //The "mouse exited" event. This MouseEvent occurs when the mouse cursor exits the unobscured part of component's geometry.
        Start_ServerBtn.setForeground(new Color(136,133,210));//Changing the color to purple
    }//GEN-LAST:event_Start_ServerBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(The_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(The_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(The_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(The_Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new The_Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Errorlbl;
    private javax.swing.JLabel MinimizeBtn;
    private javax.swing.JLabel ServerImage;
    private javax.swing.JButton Start_ServerBtn;
    private javax.swing.JLabel Successlbl;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel navigation_bar;
    // End of variables declaration//GEN-END:variables
}
